services:
  web:
    build:
      context: .
      dockerfile: docker/opencart/Dockerfile
    platform: linux/amd64
    volumes:
      - ocstore_data:/web/storage
    ports:
      - "8010:80"
    restart: unless-stopped
    env_file: ".env"
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mariadb:10.2.7
    platform: linux/amd64
    restart: unless-stopped
    env_file: ".env"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  ocstore_data:
